# Generated by Django 5.1.4 on 2026-03-12 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeSecondment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApproverAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_type', models.CharField(choices=[('college_admin', 'College Admin'), ('dept_chair', 'Department Chair'), ('office_admin', 'Office Admin'), ('admin_secondment', 'Administrative Secondment'), ('student_assistant', 'Student Assistant')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='approverflowconfig',
            name='clearance_timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_flow_configs', to='FC.clearancetimeline'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='target_colleges',
            field=models.ManyToManyField(blank=True, to='FC.college'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='target_departments',
            field=models.ManyToManyField(blank=True, to='FC.department'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='target_faculty',
            field=models.ManyToManyField(blank=True, to='FC.faculty'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='target_offices',
            field=models.ManyToManyField(blank=True, to='FC.office'),
        ),
        migrations.AlterField(
            model_name='approverflowconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver_flow_configs', to='FC.user'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FC.user'),
        ),
        migrations.AlterField(
            model_name='studentassistant',
            name='supervisor_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_assistants', to='FC.user'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FC.user'),
        ),
        migrations.AddConstraint(
            model_name='clearancerequest',
            constraint=models.UniqueConstraint(fields=('request_id',), name='uniq_request_id'),
        ),
        migrations.AddField(
            model_name='administrativesecondment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FC.user'),
        ),
        migrations.AddField(
            model_name='administrativesecondment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FC.department'),
        ),
        migrations.AddField(
            model_name='administrativesecondment',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FC.office'),
        ),
        migrations.AddField(
            model_name='administrativesecondment',
            name='primary_approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_secondments', to='FC.user'),
        ),
        migrations.AddField(
            model_name='administrativesecondment',
            name='secondment_approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondment_assignments', to='FC.user'),
        ),
        migrations.AddField(
            model_name='approverassistant',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assistants', to='FC.user'),
        ),
        migrations.AddField(
            model_name='approverassistant',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_assignments', to='FC.user'),
        ),
        migrations.AddField(
            model_name='approverassistant',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FC.college'),
        ),
        migrations.AddField(
            model_name='approverassistant',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FC.department'),
        ),
        migrations.AddField(
            model_name='approverassistant',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FC.office'),
        ),
        migrations.AddField(
            model_name='approverassistant',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver_supervised_assistants', to='FC.user'),
        ),
        migrations.AlterUniqueTogether(
            name='administrativesecondment',
            unique_together={('primary_approver', 'secondment_approver', 'department', 'office')},
        ),
        migrations.AlterUniqueTogether(
            name='approverassistant',
            unique_together={('assistant', 'supervisor', 'assistant_type')},
        ),
    ]
