# Generated by Django 5.1.4 on 2026-03-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0002_add_clearance_timeline_to_approver_flow_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('approved_clearance', 'approved_clearance'), ('rejected_clearance', 'rejected_clearance'), ('create_request', 'create_request'), ('created_requirements', 'created_requirements'), ('edited_requirements', 'edited_requirements'), ('deleted_requirements', 'deleted_requirements'), ('edited_announcement', 'edited_announcement'), ('user_logout', 'user_logout'), ('added_assistant_approver', 'added_assistant_approver'), ('updated_assistant_approver', 'updated_assistant_approver'), ('removed_assistant_approver', 'removed_assistant_approver'), ('created_guideline', 'created_guideline'), ('edited_guideline', 'edited_guideline'), ('enabled_guideline', 'enabled_guideline'), ('disabled_guideline', 'disabled_guideline'), ('archived_guideline', 'archived_guideline'), ('created_announcement', 'created_announcement'), ('enabled_announcement', 'enabled_announcement'), ('disabled_announcement', 'disabled_announcement'), ('deleted_announcement', 'deleted_announcement'), ('active_timeline', 'active_timeline'), ('inactive_timeline', 'inactive_timeline'), ('created_college', 'created_college'), ('edited_college', 'edited_college'), ('deleted_college', 'deleted_college'), ('created_department', 'created_department'), ('edited_department', 'edited_department'), ('deleted_department', 'deleted_department'), ('created_office', 'created_office'), ('edited_office', 'edited_office'), ('deleted_office', 'deleted_office')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='FC.college'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='FC.department'),
        ),
        migrations.CreateModel(
            name='FacultyDumpArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_start', models.IntegerField()),
                ('academic_year_end', models.IntegerField()),
                ('term', models.CharField(choices=[('1ST', '1ST'), ('2ND', '2ND'), ('INTERSESSION', 'INTERSESSION')], max_length=20)),
                ('dump_file_path', models.CharField(max_length=500)),
                ('dump_file_size', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clearance_timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_dumps', to='FC.clearancetimeline')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
