# Generated by Django 5.1.4 on 2026-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0003_add_timeline_indexes'),
    ]

    operations = [
        # This migration is kept for compatibility but performs no operations
        # as the fields it was supposed to modify don't exist in the current model state
    ]
