# Generated by Django 5.1.4 on 2026-03-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0008_remove_activitylog_requirement_id'),
    ]

    operations = [
        # This migration is kept for compatibility but performs no operations
        # as the field it was supposed to remove doesn't exist in the current model state
    ]
