# Generated by Django 5.1.4 on 2026-03-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0009_remove_activitylog_actor_admin_id'),
    ]

    operations = [
        # This migration is kept for compatibility but performs no operations
        # as the fields it was supposed to remove don't exist in the current model state
    ]
