# Generated by Django 5.1.4 on 2026-03-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FC", "0010_remove_activitylog_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="is_superadmin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="user_role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
