# Generated by Django 5.1.7 on 2026-03-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0003_alter_activitylog_event_type_and_more'),
        ('FC', '0010_remove_activitylog_is_staff_and_more'),
    ]

    operations = [
    ]
