# Generated by Django 5.1.4 on 2026-03-21 10:09

import django.db.models.deletion
from django.db import migrations, models


def rename_indexes_if_present(apps, schema_editor):
    connection = schema_editor.connection
    vendor = connection.vendor
    rename_map = [
        ("FC_clearance", "FC_clearanc_academi_7f9c77_idx", "FC_clearanc_academi_e5d704_idx"),
        ("FC_clearance", "FC_clearanc_faculty_f42c13_idx", "FC_clearanc_faculty_28eaba_idx"),
        ("FC_clearancerequest", "FC_clearanc_clearan_7dff0a_idx", "FC_clearanc_clearan_a77ae5_idx"),
        ("FC_clearancerequest", "FC_clearanc_status_5c4b44_idx", "FC_clearanc_status_2c2a92_idx"),
        ("FC_clearancetimeline", "FC_clearanc_is_acti_ae2d65_idx", "FC_clearanc_is_acti_9a9351_idx"),
        ("FC_clearancetimeline", "FC_clearanc_academi_4d3f82_idx", "FC_clearanc_academi_805d74_idx"),
        ("FC_clearancetimeline", "FC_clearanc_term_9f7df6_idx", "FC_clearanc_term_b68d08_idx"),
    ]

    with connection.cursor() as cursor:
        for table_name, old_name, new_name in rename_map:
            if vendor == "mysql":
                cursor.execute(
                    """
                    SELECT 1
                    FROM information_schema.statistics
                    WHERE table_schema = DATABASE()
                      AND table_name = %s
                      AND index_name = %s
                    LIMIT 1
                    """,
                    [table_name, old_name],
                )
                old_exists = cursor.fetchone() is not None
                cursor.execute(
                    """
                    SELECT 1
                    FROM information_schema.statistics
                    WHERE table_schema = DATABASE()
                      AND table_name = %s
                      AND index_name = %s
                    LIMIT 1
                    """,
                    [table_name, new_name],
                )
                new_exists = cursor.fetchone() is not None
                if old_exists and not new_exists:
                    cursor.execute(
                        f"ALTER TABLE `{table_name}` RENAME INDEX `{old_name}` TO `{new_name}`"
                    )


def rename_indexes_if_present_reverse(apps, schema_editor):
    connection = schema_editor.connection
    vendor = connection.vendor
    rename_map = [
        ("FC_clearance", "FC_clearanc_academi_e5d704_idx", "FC_clearanc_academi_7f9c77_idx"),
        ("FC_clearance", "FC_clearanc_faculty_28eaba_idx", "FC_clearanc_faculty_f42c13_idx"),
        ("FC_clearancerequest", "FC_clearanc_clearan_a77ae5_idx", "FC_clearanc_clearan_7dff0a_idx"),
        ("FC_clearancerequest", "FC_clearanc_status_2c2a92_idx", "FC_clearanc_status_5c4b44_idx"),
        ("FC_clearancetimeline", "FC_clearanc_is_acti_9a9351_idx", "FC_clearanc_is_acti_ae2d65_idx"),
        ("FC_clearancetimeline", "FC_clearanc_academi_805d74_idx", "FC_clearanc_academi_4d3f82_idx"),
        ("FC_clearancetimeline", "FC_clearanc_term_b68d08_idx", "FC_clearanc_term_9f7df6_idx"),
    ]

    with connection.cursor() as cursor:
        for table_name, old_name, new_name in rename_map:
            if vendor == "mysql":
                cursor.execute(
                    """
                    SELECT 1
                    FROM information_schema.statistics
                    WHERE table_schema = DATABASE()
                      AND table_name = %s
                      AND index_name = %s
                    LIMIT 1
                    """,
                    [table_name, old_name],
                )
                old_exists = cursor.fetchone() is not None
                cursor.execute(
                    """
                    SELECT 1
                    FROM information_schema.statistics
                    WHERE table_schema = DATABASE()
                      AND table_name = %s
                      AND index_name = %s
                    LIMIT 1
                    """,
                    [table_name, new_name],
                )
                new_exists = cursor.fetchone() is not None
                if old_exists and not new_exists:
                    cursor.execute(
                        f"ALTER TABLE `{table_name}` RENAME INDEX `{old_name}` TO `{new_name}`"
                    )


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0011_add_activitylog_admin_fields'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_present, rename_indexes_if_present_reverse),
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('approved_clearance', 'approved_clearance'), ('rejected_clearance', 'rejected_clearance'), ('create_request', 'create_request'), ('created_requirements', 'created_requirements'), ('edited_requirements', 'edited_requirements'), ('deleted_requirements', 'deleted_requirements'), ('edited_announcement', 'edited_announcement'), ('user_login', 'user_login'), ('user_logout', 'user_logout'), ('added_assistant_approver', 'added_assistant_approver'), ('updated_assistant_approver', 'updated_assistant_approver'), ('removed_assistant_approver', 'removed_assistant_approver'), ('created_guideline', 'created_guideline'), ('edited_guideline', 'edited_guideline'), ('enabled_guideline', 'enabled_guideline'), ('disabled_guideline', 'disabled_guideline'), ('delete_guideline', 'delete_guideline'), ('archived_guideline', 'archived_guideline'), ('created_announcement', 'created_announcement'), ('enabled_announcement', 'enabled_announcement'), ('disabled_announcement', 'disabled_announcement'), ('deleted_announcement', 'deleted_announcement'), ('active_timeline', 'active_timeline'), ('inactive_timeline', 'inactive_timeline'), ('created_college', 'created_college'), ('edited_college', 'edited_college'), ('deleted_college', 'deleted_college'), ('created_department', 'created_department'), ('edited_department', 'edited_department'), ('deleted_department', 'deleted_department'), ('created_office', 'created_office'), ('edited_office', 'edited_office'), ('deleted_office', 'deleted_office')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='FC.college'),
        ),
        migrations.AlterField(
            model_name='systemanalytics',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='FC.department'),
        ),
    ]
