# Generated by Django 5.1.4 on 2026-03-26 14:01

import django.db.models.deletion
from django.db import migrations, models


def rename_indexes_if_present(apps, schema_editor):
    connection = schema_editor.connection
    vendor = connection.vendor
    rename_map = [
        ("FC_clearance", "FC_clearanc_academi_7f9c77_idx", "FC_clearanc_academi_e5d704_idx"),
        ("FC_clearance", "FC_clearanc_faculty_f42c13_idx", "FC_clearanc_faculty_28eaba_idx"),
        ("FC_clearancerequest", "FC_clearanc_clearan_7dff0a_idx", "FC_clearanc_clearan_a77ae5_idx"),
        ("FC_clearancerequest", "FC_clearanc_status_5c4b44_idx", "FC_clearanc_status_2c2a92_idx"),
        ("FC_clearancetimeline", "FC_clearanc_is_acti_ae2d65_idx", "FC_clearanc_is_acti_9a9351_idx"),
        ("FC_clearancetimeline", "FC_clearanc_academi_4d3f82_idx", "FC_clearanc_academi_805d74_idx"),
        ("FC_clearancetimeline", "FC_clearanc_term_9f7df6_idx", "FC_clearanc_term_b68d08_idx"),
    ]

    with connection.cursor() as cursor:
        for table_name, old_name, new_name in rename_map:
            if vendor == "mysql":
                try:
                    cursor.execute(
                        """
                        SELECT 1
                        FROM information_schema.statistics
                        WHERE table_schema = DATABASE()
                          AND table_name = %s
                          AND index_name = %s
                        LIMIT 1
                        """,
                        [table_name, old_name],
                    )
                    old_exists = cursor.fetchone() is not None
                    cursor.execute(
                        """
                        SELECT 1
                        FROM information_schema.statistics
                        WHERE table_schema = DATABASE()
                          AND table_name = %s
                          AND index_name = %s
                        LIMIT 1
                        """,
                        [table_name, new_name],
                    )
                    new_exists = cursor.fetchone() is not None
                    if old_exists and not new_exists:
                        cursor.execute(
                            f"ALTER TABLE `{table_name}` RENAME INDEX `{old_name}` TO `{new_name}`"
                        )
                except Exception as e:
                    print(f"Warning: Could not rename index {old_name} to {new_name}: {e}")
                    continue


def rename_indexes_if_present_reverse(apps, schema_editor):
    connection = schema_editor.connection
    vendor = connection.vendor
    rename_map = [
        ("FC_clearance", "FC_clearanc_academi_e5d704_idx", "FC_clearanc_academi_7f9c77_idx"),
        ("FC_clearance", "FC_clearanc_faculty_28eaba_idx", "FC_clearanc_faculty_f42c13_idx"),
        ("FC_clearancerequest", "FC_clearanc_clearan_a77ae5_idx", "FC_clearanc_clearan_7dff0a_idx"),
        ("FC_clearancerequest", "FC_clearanc_status_2c2a92_idx", "FC_clearanc_status_5c4b44_idx"),
        ("FC_clearancetimeline", "FC_clearanc_is_acti_9a9351_idx", "FC_clearanc_is_acti_ae2d65_idx"),
        ("FC_clearancetimeline", "FC_clearanc_academi_805d74_idx", "FC_clearanc_academi_4d3f82_idx"),
        ("FC_clearancetimeline", "FC_clearanc_term_b68d08_idx", "FC_clearanc_term_9f7df6_idx"),
    ]

    with connection.cursor() as cursor:
        for table_name, old_name, new_name in rename_map:
            if vendor == "mysql":
                try:
                    cursor.execute(
                        """
                        SELECT 1
                        FROM information_schema.statistics
                        WHERE table_schema = DATABASE()
                          AND table_name = %s
                          AND index_name = %s
                        LIMIT 1
                        """,
                        [table_name, old_name],
                    )
                    old_exists = cursor.fetchone() is not None
                    cursor.execute(
                        """
                        SELECT 1
                        FROM information_schema.statistics
                        WHERE table_schema = DATABASE()
                          AND table_name = %s
                          AND index_name = %s
                        LIMIT 1
                        """,
                        [table_name, new_name],
                    )
                    new_exists = cursor.fetchone() is not None
                    if old_exists and not new_exists:
                        cursor.execute(
                            f"ALTER TABLE `{table_name}` RENAME INDEX `{old_name}` TO `{new_name}`"
                        )
                except Exception as e:
                    print(f"Warning: Could not rename index {old_name} to {new_name}: {e}")
                    continue


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0011_merge_20260323_1750'),
    ]

    operations = [
        migrations.RunPython(rename_indexes_if_present, rename_indexes_if_present_reverse),
        migrations.AddField(
            model_name='requirement',
            name='approver_flow_step',
            field=models.ForeignKey(blank=True, help_text='Select which approver flow step this requirement belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='FC.approverflowstep'),
        ),
    ]
