# Generated by Django 5.1.7 on 2026-03-26 00:00
 
from django.db import migrations, models
 
 
class Migration(migrations.Migration):
 
    dependencies = [
        ("FC", "0011_merge_20260323_1750"),
    ]
 
    operations = [
        migrations.AddField(
            model_name="notification",
            name="user_role",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]