# Generated by Django 5.1.4 on 2026-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC', '0012_rename_fc_clearanc_academi_7f9c77_idx_fc_clearanc_academi_e5d704_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('approved_clearance', 'approved_clearance'), ('rejected_clearance', 'rejected_clearance'), ('create_request', 'create_request'), ('created_requirements', 'created_requirements'), ('edited_requirements', 'edited_requirements'), ('deleted_requirements', 'deleted_requirements'), ('edited_announcement', 'edited_announcement'), ('user_logout', 'user_logout'), ('added_assistant_approver', 'added_assistant_approver'), ('updated_assistant_approver', 'updated_assistant_approver'), ('removed_assistant_approver', 'removed_assistant_approver'), ('created_guideline', 'created_guideline'), ('edited_guideline', 'edited_guideline'), ('enabled_guideline', 'enabled_guideline'), ('disabled_guideline', 'disabled_guideline'), ('delete_guideline', 'delete_guideline'), ('archived_guideline', 'archived_guideline'), ('created_announcement', 'created_announcement'), ('enabled_announcement', 'enabled_announcement'), ('disabled_announcement', 'disabled_announcement'), ('deleted_announcement', 'deleted_announcement'), ('active_timeline', 'active_timeline'), ('inactive_timeline', 'inactive_timeline'), ('created_college', 'created_college'), ('edited_college', 'edited_college'), ('deleted_college', 'deleted_college'), ('created_department', 'created_department'), ('edited_department', 'edited_department'), ('deleted_department', 'deleted_department'), ('created_office', 'created_office'), ('edited_office', 'edited_office'), ('deleted_office', 'deleted_office')], max_length=50),
        ),
    ]
