# Generated by Django 5.1.7 on 2026-03-26 00:00
 
from django.db import migrations, models
 
 
class Migration(migrations.Migration):
 
    dependencies = [
        ("FC", "0012_notification_user_role"),
    ]
 
    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("approved", "approved"), ("rejected", "rejected"), ("submitted", "submitted")],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
 