# Generated by Django 5.1.7 on 2026-03-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FC", "0013_notification_status_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approver_notifications",
                to="FC.user",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_notifications",
                to="FC.user",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="clearance_period_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="clearance_period_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
