# Generated by Django 5.1.4 on 2026-03-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FC", "0015_alter_activitylog_event_type_add_timeline_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="event_type",
            field=models.CharField(
                max_length=50,
                choices=[
                    ("approved_clearance", "approved_clearance"),
                    ("rejected_clearance", "rejected_clearance"),
                    ("create_request", "create_request"),
                    ("created_requirements", "created_requirements"),
                    ("edited_requirements", "edited_requirements"),
                    ("deleted_requirements", "deleted_requirements"),
                    ("edited_announcement", "edited_announcement"),
                    ("user_login", "user_login"),
                    ("user_logout", "user_logout"),
                    ("added_assistant_approver", "added_assistant_approver"),
                    ("updated_assistant_approver", "updated_assistant_approver"),
                    ("removed_assistant_approver", "removed_assistant_approver"),
                    ("created_guideline", "created_guideline"),
                    ("edited_guideline", "edited_guideline"),
                    ("enabled_guideline", "enabled_guideline"),
                    ("disabled_guideline", "disabled_guideline"),
                    ("delete_guideline", "delete_guideline"),
                    ("archived_guideline", "archived_guideline"),
                    ("created_announcement", "created_announcement"),
                    ("enabled_announcement", "enabled_announcement"),
                    ("disabled_announcement", "disabled_announcement"),
                    ("deleted_announcement", "deleted_announcement"),
                    ("created_timeline", "created_timeline"),
                    ("edited_timeline", "edited_timeline"),
                    ("archived_timeline", "archived_timeline"),
                    ("enabled_timeline", "enabled_timeline"),
                    ("disabled_timeline", "disabled_timeline"),
                    ("active_timeline", "active_timeline"),
                    ("inactive_timeline", "inactive_timeline"),
                    ("created_college", "created_college"),
                    ("edited_college", "edited_college"),
                    ("deleted_college", "deleted_college"),
                    ("created_department", "created_department"),
                    ("edited_department", "edited_department"),
                    ("deleted_department", "deleted_department"),
                    ("created_office", "created_office"),
                    ("edited_office", "edited_office"),
                    ("deleted_office", "deleted_office"),
                ],
            ),
        ),
    ]
